CREATE TABLE persona(
    id int primary key auto_increment,
    nombre varchar,
    apellido varchar,
    telefono int,
    email varchar
);


CREATE TABLE producto(
    id int primary key auto_increment,
    nombre varchar,
    descripcion varchar,
    stock int 
);


CREATE TABLE compra(
    id_persona int,
    id_producto int,
    fecha_hora datetime,
    foreign key(id_persona) references persona(id),
    foreign key(id_producto) references producto(id),
    primary key(id_persona,id_producto,fecha_hora);
)